Microwave/Models/MicrowaveModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Microwave.Models
{
    public class MicrowaveModel
    {
        [Display(Name = "Tipo do prato")]
        public PratosModel NovoPrato { get; set; }

        [Display(Name = "Tempo")]      
        public string tempo { get; set; }       

        [Display(Name = "Minutos")]
        [Range(0,59, ErrorMessage = "<span class='text-danger'>Número inválido</span>")]
        public int minutos { get; set; }

        [Display(Name = "Segundos")]
        [Range(0, 59, ErrorMessage = "<span class='text-danger'>Número inválido</span>")]
        public int segundos { get; set; }

        [Display(Name = "Potencia")]
        [Range(0, 10, ErrorMessage = "<span class='text-danger'>Número inválido</span>")]
        public int potencia { get; set; } = 10;

        public string prato { get; set; }

        

        public MicrowaveModel ()
        {
            NovoPrato = new PratosModel();
        }
    }
}

Microwave/Models/PratosModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Microwave.Models
{
    public class PratosModel
    {
        [Display(Name = "Nome do prato")]
        [Required(ErrorMessage = "<span class='text-danger'>Este campo é obrigatório!</span>")]
        public string nome { get; set; }

        [Display(Name = "Modo de preparo")]
        [Required(ErrorMessage = "<span class='text-danger'>Este campo é obrigatório!</span>")]
        public string instrucao { get; set; }

        [Display(Name = "Minutos")]
        [Range(0, 60, ErrorMessage = "<span class='text-danger'>Número inválido</span>")]
        [Required(ErrorMessage = "<span class='text-danger'>Este campo é obrigatório!</span>")]
        public int minutos { get; set; }

        [Display(Name = "Segundos")]
        [Range(0, 60, ErrorMessage = "<span class='text-danger'>Número inválido</span>")]
        [Required(ErrorMessage = "<span class='text-danger'>Este campo é obrigatório!</span>")]
        public int segundos { get; set; }

        [Display(Name = "Potencia")]
        public int potencia { get; set; } = 10;

        public List<object> PratosList = new List<object>();

        public void setPratosDefault()
        {
            PratosList.Add(new
            {
                nome = "Frango",
                instrucao = "Corte em pedaços pequenos, leve ao microondas em um recipiente apropriado, interrompa o processo para mexer se necessário.",
                minutos = 25,
                segundos = 0,
                potencia = 10,
                value = $"Frango;25;0;10;Corte em pedaços pequenos, leve ao microondas em um recipiente apropriado, interrompa o processo para mexer se necessário."
            });

            PratosList.Add(new 
            {
                nome = "Carne",
                instrucao = "Pode se cortar em pedaços médios ou pequenos, leve ao microondas em um recipiente apropriado.",
                minutos = 20,
                segundos = 0,
                potencia = 10,
                value = $"Carne;20;0;10;Pode se cortar em pedaços médios ou pequenos, leve ao microondas em um recipiente apropriado."
            });

            PratosList.Add(new 
            {
                nome = "Peixe",
                instrucao = "Corte em pedaços médios ou grandes, leve ao microondas em um recipiente apropriado, interrompa o processo para mexer se necessário",
                minutos = 15,
                segundos = 0,
                potencia = 8,
                value = $"Peixe;15;0;8;Corte em pedaços médios ou grandes, leve ao microondas em um recipiente apropriado, interrompa o processo para mexer se necessário"
            });

            PratosList.Add(new 
            {
                nome = "Arroz",
                instrucao = "Coloque os ingredientes em um recipiente apropriado, adicione 2x a quantidade de água, leve ao microondas",
                minutos = 15,
                segundos = 30,
                potencia = 8,
                value = $"Arroz;15;30;8;Coloque os ingredientes em um recipiente apropriado, adicione 2x a quantidade de água, leve ao microondas"
            });

            PratosList.Add(new 
            {
                nome = "Pipoca",
                instrucao = "Coloque no microondas a pipoca com o lado informado virado para cima.",
                minutos = 1,
                segundos = 30,
                potencia = 7,
                value = $"Pipoca;1;30;7;Coloque no microondas a pipoca com o lado informado virado para cima."
            });
        }
    }
}

Microwave/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microwave.Models;

namespace Microwave.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return Redirect("/Microwave");
        }       
    }
}

Microwave/Controllers/MicrowaveController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microwave.Models;
using System;
using System.Collections.Generic;

namespace Microwave.Controllers
{
    public class MicrowaveController : Controller
    {
        public IActionResult Index()
        {
            var Microwave = new MicrowaveModel();
            Microwave.NovoPrato.setPratosDefault();            
            return View(Microwave);
        }
    }
}   

Microwave/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Microwave/Views/Microwave/Index.cshtml
@model Microwave.Models.MicrowaveModel
@{ 
    ViewData["Title"] = "Benner";
}
<div class="panel panel-info">
    <div class="panel-heading text-center">
        <h4><strong><span class="text-danger">Benner</span></strong>Wave</h4>
    </div>
    <div class="panel-body">
        <div class="form-group">
            <div class="col-md-7">
                <div class="panel panel-default" style="margin-bottom: 0;">
                    <div class="panel-body d-flex align-items-center justify-content-around" style="min-height: 500px;" id="feedback">
                        <div class="form-group text-center text-info">
                            <span class="glyphicon glyphicon-fire" style="font-size: 8em"></span>
                            <h3>Aguardando...</h3>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <form asp-action="Index" asp-controller="Microwave" id="FormMicrowave" method="post">
                    <div class="row">
                        <div class="col-md-12">                           
                            <h1 class="text-right"><span id="tempo">00:00</span></h1>
                            <hr />
                        </div>                        
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label asp-for="minutos"></label>   <span asp-validation-for="minutos"></span>
                            <div class="input-group">
                                <div class="input-group-btn">
                                    <button type="button" id="btnSubMin" class="btn btn-lg btn-default" onclick="SubtraiMinuto(document.getElementById('minutos').value)"><i class="glyphicon glyphicon-minus"></i></button>
                                </div>
                                <input type="number" min="0" max="59" step="1" class="form-control input-lg text-center" asp-for="minutos" required />
                                <div class="input-group-btn">
                                    <button type="button" class="btn btn-lg btn-default" onclick="SomaMinuto(document.getElementById('minutos').value)"><i class="glyphicon glyphicon-plus"></i></button>
                                </div>
                            </div>                            
                        </div>
                        <div class="col-md-6">
                            <label for="btnStart">&nbsp;</label>
                            <button class="btn btn-lg btn-block btn-primary" id="btnStart" value="start" onclick="IniciarCronometro('start')"><i class="glyphicon glyphicon-play"></i>&nbsp;Iniciar</button>
                        </div>
                    </div>                                            
                    <div class="row">
                        <div class="col-md-6">
                            <label asp-for="segundos"></label> <span asp-validation-for="segundos"></span>
                            <div class="input-group">
                                <div class="input-group-btn">
                                    <button type="button" class="btn btn-lg btn-default" onclick="SubtraiSegundo(document.getElementById('segundos').value)"><i class="glyphicon glyphicon-minus"></i></button>
                                </div>
                                <input type="number" min="0" max="59" step="1" class="form-control input-lg text-center" asp-for="segundos" required />
                                <div class="input-group-btn">
                                    <button type="button" class="btn btn-lg btn-default" onclick="SomaSegundo(document.getElementById('segundos').value)"><i class="glyphicon glyphicon-plus"></i></button>
                                </div>
                            </div>                            
                        </div>    
                        <div class="col-md-6">
                            <label for="btnPause">&nbsp;</label>
                            <button type="button" id="btnPause" disabled value="pause" onclick="PausarCronometro()" class="btn btn-block btn-lg btn-warning"><i class="glyphicon glyphicon-pause"></i>&nbsp;Pausar</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label asp-for="potencia"></label>
                            <div class="input-group">
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-lg btn-danger" onclick="Subtrai(document.getElementById('potencia').value)"><i class="glyphicon glyphicon-minus"></i></button>
                                </span>
                                <input type="number" min="0" max="10" step="1" class="form-control input-lg text-center" asp-for="potencia" />
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-lg btn-success" onclick="Soma(document.getElementById('potencia').value)"><i class="glyphicon glyphicon-plus"></i></button>
                                </span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label for="btnCancelar">&nbsp;</label>
                            <button type="button" id="btnStop" value="stop" disabled onclick="ResetarCronometro()" class="btn btn-lg btn-block btn-danger"><i class="glyphicon glyphicon-remove"></i>&nbsp;Cancelar</button>
                        </div>
                    </div>
                </form>                
                    <div class="form-group">
                        <label asp-for="NovoPrato"></label>
                        <div class="input-group">
                            @Html.DropDownListFor(Model => Model.prato, new SelectList(Model.NovoPrato.PratosList, "value", "nome", Model.prato), "-- Selecione um prato --", new { @class = "form-control" })
                            <div class="input-group-addon">
                                <a href="#" data-toggle="modal" data-target="#ModalNovoPrato" title="Adicionar novo prato!"><i class="glyphicon glyphicon-plus"></i></a>
                            </div>
                        </div>
                    </div>
                
                <div class="row">
                    <div class="col-md-12">                        
                        <script>
                            document.getElementById('prato').addEventListener('change', (e) => {
                                let result = e.target.value;
                                result = result.split(";");                                
                                document.getElementById('minutos').value = result[1];
                                document.getElementById('segundos').value = result[2];
                                document.getElementById('potencia').value = result[3];
                                document.getElementById('instrucao').innerHTML = result[4];
                            })                            
                        </script>
                        <p id="instrucao"></p>
                    </div>
                </div>                
            </div>            
        </div>
    </div>
   
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="ModalNovoPrato">
    <div class="modal-dialog modal-lg" role="document">
        @Html.Partial("NovoPrato", Model.NovoPrato)
    </div>
</div>

Microwave/Views/Shared/NovoPrato.cshtml
@model Microwave.Models.PratosModel
<div class="modal-content">
    <div class="modal-header text-info bg-info text-center">
        <button type="button" class="close" data-dismiss="modal" aria-label="close"><span aria-hidden="true"></span>&times;</button>
        <strong>Novo Prato</strong>
    </div>
    <div class="modal-body">
        <form onsubmit="AdicionarPrato()" id="NovoPratoForm">
            <div class="row">
                <div class="col-md-6">
                    <label asp-for="nome"></label> <span asp-validation-for="nome"></span>
                    <input type="text" class="form-control" asp-for="nome" id="nomePrato" required />
                </div>
                <div class="col-md-3">
                    <label asp-for="minutos"></label> <span asp-validation-for="minutos"></span>
                    <input type="number" min="0" max="59" step="1" required asp-for="minutos" id="novoMinuto" class="form-control" />
                </div>
                <div class="col-md-3">
                    <label asp-for="segundos"></label> <span asp-validation-for="segundos"></span>
                    <input type="number" min="0" max="59" step="1" required asp-for="segundos" id="novoSegundo" class="form-control" />
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label asp-for="potencia"></label>
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button type="button" class="btn btn-danger" onclick="SubtraiModal(document.getElementById('potenciaPrato').value)"><i class="glyphicon glyphicon-minus"></i></button>
                        </span>
                        <input type="number" min="0" max="10" step="1" class="form-control text-center" id="potenciaPrato" asp-for="potencia" required />
                        <span class="input-group-btn">
                            <button type="button" class="btn btn-success" onclick="SomaModal(document.getElementById('potenciaPrato').value)"><i class="glyphicon glyphicon-plus"></i></button>
                        </span>
                    </div>
                    <script>
                        function SubtraiModal(valor) {                            
                            if (valor <= 1) {
                                return document.getElementById('potenciaPrato').value = 1;
                            }
                            document.getElementById('potenciaPrato').value = --valor;
                        }
                        function SomaModal(valor) {
                            if (valor >= 10) {
                                return document.getElementById('potenciaPrato').value = 10;
                            }
                            document.getElementById('potenciaPrato').value = ++valor;
                        }
                    </script>
                </div>
                <div class="col-md-9">
                    <label asp-for="instrucao"></label> <span asp-validation-for="instrucao"></span>
                    <textarea id="novaInstrucao" class="form-control" asp-for="instrucao"></textarea>
                </div>
            </div>                       
            <button id="btnReset" type="reset" class="hidden"></button>
        </form>
    </div>
    <div class="modal-footer text-right">        
        <button class="btn btn-success" type="button" onclick="AdicionarPrato()" ><i class="glyphicon glyphicon-ok"></i>&nbsp;Salvar</button>
    </div>
</div>

<script>
    function AdicionarPrato() {
        let select = document.getElementById('prato');
        let nome = document.getElementById('nomePrato').value;
        let minuto = document.getElementById('novoMinuto').value;
        let segundo = document.getElementById('novoSegundo').value;
        let potencia = document.getElementById('potenciaPrato').value;
        let instrucao = $("#novaInstrucao").val();
        $("#prato").append(`<option value="${nome};${minuto};${segundo};${potencia};${instrucao}">${nome}</option>`)        
        nome.value = "";
        minuto.value = "";
        segundo.value = "";
        potencia.value = "";
        instrucao.value = "";
        $(".close").click();
        $("#btnReset").click();
    }
</script>

Microwave/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Microwave</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body class="h-100 gray-bg d-flex align-items-center justify-content-around">

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="text-right">
            <p>&copy; 2018 - Leonardo Larocca</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>        
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>        

    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>